"""empty message

Revision ID: 019a7a882d3f
Revises: ec450412a8f6
Create Date: 2021-07-23 15:03:02.840046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019a7a882d3f'
down_revision = 'ec450412a8f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_prompt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dialect_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=2000), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('changed_on', sa.DateTime(), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text_transcription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_transcription_id', sa.Integer(), nullable=False),
    sa.Column('source_dialect_id', sa.Integer(), nullable=False),
    sa.Column('dest_dialect_id', sa.Integer(), nullable=False),
    sa.Column('text_transcription', sa.String(length=2000), nullable=False),
    sa.Column('quality', sa.Integer(), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text_transcription')
    op.drop_table('text_prompt')
    # ### end Alembic commands ###
